apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nginx.10.237.198.16.xip.io`)
      kind: Rule
      services:
        - name: nginx
          port: 80

