---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: keel
  namespace: keel
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: keel
  values:
    file: values.yaml
  chart:
    repository: https://charts.keel.sh
    name: keel
#    version: 0.9.3
    service:
      type: ClusterIP
#  valuesFrom:
#  - externalSourceRef:
#      url: https://raw.githubusercontent.com/dilerous/kubernetes_lab_gitops/master/keel/values.yaml
