---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.7
spec:
  releaseName: vault-secrets-operator
  rollback:
    enable: true
  chart:
    git: https://github.com/ricoberger/vault-secrets-operator
    ref: master
    path: charts/vault-secrets-operator
  values:
    replicaCount: 1
    deploymentStrategy:
      type: Recreate
    vault:
      address: "http://vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
      reconciliationTime: "300"
